# Generated by Django 5.1.8 on 2025-04-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklogs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoReport',
        ),
        migrations.AddField(
            model_name='worklog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project-images/'),
        ),
    ]
