# Generated by Django 5.1.8 on 2025-04-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklogs', '0002_delete_photoreport_worklog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
