# Generated by Django 5.1.8 on 2026-06-15 21:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklogs', '0003_alter_worklog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
