# Generated by Django 5.1.8 on 2026-06-19 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worklogs', '0004_alter_worklog_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklog',
            name='image',
        ),
    ]
