# Generated by Django 5.1.6 on 2025-03-18 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_payment_company_salary_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='manager',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 'manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='manager_salaries', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salary',
            name='worker',
            field=models.ForeignKey(limit_choices_to={'role': 'worker'}, on_delete=django.db.models.deletion.CASCADE, related_name='worker_salaries', to=settings.AUTH_USER_MODEL),
        ),
    ]
