# Generated by Django 5.1.6 on 2025-03-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_salary_manager_alter_salary_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialreport',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
