# Generated by Django 5.1.6 on 2025-03-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_payment_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='session_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
