# Generated by Django 5.1.6 on 2025-03-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_payment_session_id_payment_session_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='session_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
