# Generated by Django 5.1.6 on 2025-03-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_alter_payment_session_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
            preserve_default=False,
        ),
    ]
