# Generated by Django 5.1.6 on 2025-03-24 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('finances', '0008_salary_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialreport',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_report', to='companies.company'),
        ),
    ]
