# Generated by Django 5.1.6 on 2025-04-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0010_payment_manager_alter_payment_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
