# Generated by Django 5.1.6 on 2025-03-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_team',
            field=models.ManyToManyField(related_name='projects', to='teams.team'),
        ),
    ]
