# Generated by Django 5.1.6 on 2025-03-11 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_start_date'),
        ('teams', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assigned_team',
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='teams.team'),
        ),
    ]
