# Generated by Django 5.1.6 on 2025-03-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_project_assigned_team_project_assigned_team'),
        ('teams', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assigned_team',
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_team',
            field=models.ManyToManyField(related_name='projects', to='teams.team'),
        ),
    ]
