# Generated by Django 5.1.8 on 2025-04-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_assigned_team_project_assigned_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project-images/'),
        ),
    ]
