# Generated by Django 5.1.8 on 2025-05-10 06:09

import apps.projects.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_assigned_team_alter_project_client'),
        ('teams', '0004_team_teams_team_name_e33a4e_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='assigned_team',
            field=models.ManyToManyField(related_name='projects', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, validators=[apps.projects.models.validate_client]),
        ),
    ]
