# Generated by Codex on 2026-06-10

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_project_assigned_team_alter_project_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='blueprint',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to='project_blueprints/',
                validators=[apps.projects.models.validate_project_blueprint_pdf],
            ),
        ),
    ]
