# Generated by Django 5.1.8 on 2025-05-10 05:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_slug'),
        ('teams', '0003_alter_team_company_alter_team_workers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['name', 'company'], name='teams_team_name_e33a4e_idx'),
        ),
    ]
