# Generated by Django 5.1.6 on 2025-03-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('worker', 'Worker'), ('client', 'Client'), ('manager', 'Manager')], max_length=10),
        ),
    ]
